version: '3.3'

services:
  markswalletdb:
    container_name: markswalletdb
    hostname: markswalletdb
    image: jeremiahldx21/markswallet_markswalletdb
    restart: always
    networks:
     - assignment2
    ports:
      - "9073:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  transactions:
    restart: always
    image: jeremiahldx21/markswallet_transactions
    container_name: transactioncontainer
    hostname: transactioncontainer
    networks:
      - assignment2
    ports:
      - 9072:9072
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - markswalletdb
  tokens:
    restart: always
    image: jeremiahldx21/markswallet_tokens
    container_name: tokenscontainer
    hostname: tokenscontainer
    networks:
      - assignment2
    ports:
      - 9071:9071
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - markswalletdb
  markswalletfrontend:
    container_name: markswalletfrontend
    hostname: markswalletfrontend
    image: jeremiahldx21/markswallet_markswalletfrontend
    restart: always
    ports:
      - "9070:80"

networks:
  assignment2:
    driver: bridge