version: '3.8'

services:
  MarksWalletdb:
    container_name: MarksWalletDatabase
    hostname: MarksWalletDatabase
    image: mysql:latest
    restart: always
    networks:
     - assignment2
    ports:
      - "9073:9073"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  Transactions:
    image: mysql:latest
    restart: always
    build:
      context: ./src/Transactions
    container_name: transactioncontainer
    hostname: transactioncontainer
    networks:
      - assignment2
    ports:
      - 9072:9072
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - MarksWalletdb
  Tokens:
    image: mysql:latest
    restart: always
    build:
      context: ./src/Tokens
    container_name: tokenscontainer
    hostname: tokenscontainer
    networks:
      - assignment2
    ports:
      - 9071:9071
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - MarksWalletdb
  markswalletweb:
    container_name: frontend
    hostname: frontend
    build: 
      context: ./src/Frontend
    restart: always
    ports:
      - "9070:9070"

networks:
  assignment2:
    driver: bridge