version: '3.3'

services:
  markswalletdb:
    container_name: markswalletdb
    hostname: markswalletdb
    image: mysql:latest
    restart: always
    networks:
     - assignment2
    ports:
      - "9073:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  transactions:
    restart: always
    build:
      context: ./src/Transactions
    container_name: transactioncontainer
    hostname: transactioncontainer
    networks:
      - assignment2
    ports:
      - 9072:9072
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - markswalletdb
  tokens:
    restart: always
    build:
      context: ./src/Token
    container_name: tokenscontainer
    hostname: tokenscontainer
    networks:
      - assignment2
    ports:
      - 9071:9071
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - markswalletdb
  frontend:
    container_name: frontend
    hostname: frontend
    build: 
      context: ./src/Frontend
    restart: always
    ports:
      - "9070:80"

networks:
  assignment2:
    driver: bridge